CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price DECIMAL(19,2) NOT NULL,
    category VARCHAR(255),
    stock INT,
    created_date TIMESTAMP,
    last_updated_date TIMESTAMP
);

CREATE INDEX idx_products_category ON products(category);